/**
 * Writes apps/web/out/sw.js: a service worker that precaches the whole static site so the
 * website works offline after the first visit. Re-run after every build (npm run build:web does).
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "apps/web/out");

const files: string[] = [];
const walk = (dir: string) => {
  for (const f of fs.readdirSync(dir)) {
    const p = path.join(dir, f);
    if (fs.statSync(p).isDirectory()) walk(p);
    else if (!/\.(map)$/.test(f) && f !== "sw.js") files.push("/" + path.relative(OUT, p).split(path.sep).join("/"));
  }
};
walk(OUT);

const hash = crypto.createHash("sha1");
for (const f of files.sort()) hash.update(f + fs.statSync(path.join(OUT, f)).size);
const version = hash.digest("hex").slice(0, 10);
const urls = files.map((f) => f.replace(/index\.html$/, ""));

const sw = `// Generated by scripts/postbuild-web.ts. Do not edit.
const CACHE = "wm-${version}";
const URLS = ${JSON.stringify(urls)};

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    for (let i = 0; i < URLS.length; i += 40) {
      await Promise.all(URLS.slice(i, i + 40).map((u) => cache.add(u).catch(() => {})));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  const isPage = req.mode === "navigate";
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (isPage) {
      try {
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch {
        return (await cache.match(req, { ignoreSearch: true })) || (await cache.match("/")) || Response.error();
      }
    }
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  })());
});
`;
fs.writeFileSync(path.join(OUT, "sw.js"), sw);
console.log(`🛰️  sw.js precaches ${urls.length} files (cache wm-${version})`);
